### ISSUE TITLE
Добавить поддержку объектов в attr

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/Snakeskin#1]
Добавить поддержку выгрузки атрибутов и их значений из объекта. Примерный синтаксис:

```
- attr @= from {
    title: {
        type: 'value', /// по умолчанию
        value: 'всплывающая подсказка',
        filters: ['ucfirs'] /// необязательное поле
    },
    placeholder: 'Foobar', /// если нужно только значение указать
    require: true, /// в случае, если у атрибута нету значения 
    ng: { /// механизм задания группы
        type: 'group',
        value: {
            show: 'show === true'
        }
    }
}
```

**Comment by kobezzza** [comment]
Будет сделано с помощью фильтра.

``` js
< .foo ${bar|attr}
```

**Comment by trikadin** [comment]
Примерная имплементация с помощью Collection.js и sugar.

``` js
/**
   * Рекурсивно разворачивает объект в атрибуты для тега.
   * Вложенные объекты становятся группами атрибутов -- их свойства
   * будут атрибутами с префиксом, равным ключу этого св-ва и дефису после него
   * (для глубоких вложенностей префиксы суммируются)
   *
   * Заглавные буквы в названии атрибута (ключе свойства) будут заменены
   * на дефис и эту букву в нижнем регистре, по аналогии с dataset у dom-элементов
   *
   * Если значением атрибута является undefined, то будет выведено только название атрибута
   * (например, {type: 'text', required: undefined} выведет как 'type="text" required'
   *
   * @param {Object} [object = {}]
   * @param {string} [prefix = ''] Префикс перед названиями атрибутов для этого объекта.
   */
function objToAttrs(object = {}, prefix = '') {
  return $C(object).reduce(
    (res, val, key) => {
      key = key.dasherize().escapeHTML();

      if (typeof val === 'object' && !Object.isNull(val)) {
        return res + objToAttrs(val, prefix + key + '-');
      } else {
        return res + prefix + key + (val === undefined ? ' ' : `="${String(val).escapeHTML()}" `);
      }
    }, ''
  );
}
```

Поскольку этот вариант я делал под свои нужды, то есть вещи, которые в нём явно стоит поменять.
- Поведение с undefined -- очень спорная штука. Я думаю, что его можно оставить, но ограничить его поведение набором атрибутов типа 'required', 'readonly', 'autofocus' и т. д., и обязательно проверять на отсутствие префикса. И тогда можно заменить undefined на true.
- Проверка на циклы. 
- В dom-режиме добавлять атрибуты к ноде.

**Comment by kobezzza** [comment]
Предложение по модели объекта для задания атрибута через фильтр attr:

``` js
{
  focused: TRUE,
  disabled: FALSE,
  foo: (val|default 'baz'),
  ng: {
    repeat: 'var key in bar'
  }
}
```

TRUE (inline атрибут) и FALSE (выключить атрибут) - это специальные константы, которые буду определены самим SS.

---

Почему я против словарей: SS используется для генерации XML подобных структур, а не только HTML, поэтому придётся писать много словарей + не понятно как их засовывать в рантайм, кроме как вставлять в виде текста в скомпиленные шаблоны. Также атрибуты привязаны к тегу, т.е. у одного тега один атрибут инлайновый, а у другого тега точно такой же - нет. Я не говорю, что именно в HTML такая ситуация есть, а вот в XML, SGML и т.д. - запросто.

**Comment by kobezzza** [comment]
Утверждённый вариант задания объектов-атрибутов:

``` js
< .foo ${{ class: 'bar' }}
```

Атрибут attr будет ставится по умолчанию. При этом, нужно отлавливать ситуации вида:

``` js
< .foo ${{ class: 'bar' }} = 1
```

И кидать исключения, т.к. это явная ошибка.

**Comment by kobezzza** [comment]
Сделано.
