### ISSUE TITLE
Don't close input

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/Snakeskin#12]
```
- block textField(multiline)
  < ${multiline ? 'textarea' : 'input'}

~= textField(false)
```

=>

``` html
<input></input>
```

**Comment by kobezzza** [comment]
Придётся добавлять рантайм обвязку.

**Comment by trikadin** [comment]
Планируешь делать это настраиваемым?

**Comment by kobezzza** [comment]
Да, это не правильное поведение.

**Comment by trikadin** [comment]
Ты не понял. Я имею в виду, ты дашь пользователю возможность указать набор тегов, которые не нужно закрывать?

**Comment by kobezzza** [comment]
Да, но ещё не решил как именно это будет выглядеть. Пока склоняюсь к простому `Snakeskin.inlineTags['textarea'] = true`

**Comment by trikadin** [comment]
Я думал массив предложить, но да, так удобнее, пожалуй. Только не inlineTags, а emptyTags -- так правильно)

И ты не хочешь это в параметры компиляции вынести? Чтобы директива, если что, могла самой себе переопределить это поведение -- мало ли какой xml она генерит.

**Comment by kobezzza** [comment]
Сам словарь в параметр компиляции нет, т.к. он юзается в рантайме и мне придётся засовывать его в скомпиленый шаблон и т.д.

Я думаю о возможности создавать группы словарей, там html, svg и т.д. и в параметре компиляции указывать, какой из словарей юзается.

**Comment by trikadin** [comment]
А в чём разница -- создать глобальный словарь и из директивы обратиться к нему по имени, или в самой директиве его объявить, а там, где он не переопределен -- брать дефолтный глобальный.

**Comment by kobezzza** [comment]
Я подумаю в общем.

**Comment by kobezzza** [comment]
> А в чём разница -- создать глобальный словарь и из директивы обратиться к нему по имени.

Проверка идёт в рантайме, поэтому на этапе трансляции нет никакой возможности определить это.

Пока остановился на варианте, когда будут группы, например,

``` js
Snakeskin.emptyTags.html = {};
Snakeskin.emptyTags.svg = {};
```

И т.д.

Параметром компиляции можно будет задавать название группы.

**Comment by trikadin** [comment]
Давай сначала определимся, на каких уровнях нам нужна возможность (до/пере)определения того, какие атрибуты инлайновые, а какие -- нет.

**Comment by kobezzza** [comment]
Сейчас в СС6 это происходит на этапе трансляции, но это не позволяет разрешать конфликты вида `${multiline ? 'textarea' : 'input'}`. Поэтому в СС7 это уходит в рантайм, поэтому словарь также обязан лежать в рантайме и он будет входит в snakeskin,live пакет.

**Comment by trikadin** [comment]
Так, то есть сами директивы не могут переопределить словари? Или даже сама директива tag.

**Comment by kobezzza** [comment]
Нет, разве что разместить словарь в скомпиленом коде - но я против этого.

**Comment by trikadin** [comment]
replace("сами директивы", "сами темплейты")

**Comment by kobezzza** [comment]
WAT

**Comment by trikadin** [comment]
Блин.

> Так, то есть сами **директивы** не могут переопределить словари? Или даже сама директива tag.

Подразумевалось:

> Так, то есть сами **темплейты** не могут переопределить словари? Или даже сама директива tag.

**Comment by kobezzza** [comment]
> разве что разместить словарь в скомпиленом коде - но я против этого.

**Comment by trikadin** [comment]
То есть, сейчас воркэраунд для случая, когда одна директива генерит HTML, вторая -- SVG, а третья -- вообще какой-то свой xml (понимаю, что искусственный пример, но всё же) -- это добавить в emptyTags кастомный объект?

**Comment by kobezzza** [comment]
Либо так, либо,

``` js
- template foo()
  @= doctype svg
    < path
```

**Comment by trikadin** [comment]
Чёт не понял.

**Comment by kobezzza** [comment]
> Чёт не понял.

Через флаги компиляции в общем.

**Comment by kobezzza** [comment]
Предложение о явном указании карты инлайн тегов. Сейчас можно воспользоваться хуком `!inline` (`:inline` в CC6) чтобы явно указать, что тег инлайновый

``` js
< foo!inline
```

Я предлагаю расширить этот синтаксис:

``` js
: svg = { &
  path: true
} .

- template foo(tag)
  < ${tag}!inline:svg
```

**Comment by trikadin** [comment]
Окей, т. е. настройка инлайновости тегов у нас будет теперь на трех уровнях -- global, template, directive?

**Comment by kobezzza** [comment]
Не многовато ли? Хочется какой то простой схемы...

Есть идея, вчера я ввёл особый виртуальный тег, который нужен исключительно для задания свойств, который будут наследовать дочерние теги (пока это только &).

А что если договорится, что свойство `!inline:reference` будет наследоваться детьми и тогда для указания ссылки на тот или иной словарь достаточно написать:

``` js
< ?!inline:svg
  < path
  < path
```

А по умолчанию все просто берут из Snakeskin.emptyTags. Кажется такой вариант наиболее простой и нет никаких флагов компиляции и групп.

**Comment by kobezzza** [comment]
``` js
: foo = {textarea: true}
  < ?!inline=foo
    < ${'textarea'}
```

**Comment by kobezzza** [comment]
Сделано.
