### ISSUE TITLE
Разработать механизм фильтров по умолчанию

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#20]
``` js
Snakeskin.addDirective(
  'attr',
  {
    filters: [{attr: ['__ATTR_CACHE__']}]
  },
  function () {

  }
);
```

Отменятся такие фильтры будут через стандартный механизм: `!attr`.

Также, есть мысли о добавление такой возможности в самом шаблоне:

``` js
- template foo(val)
  - filters [{myFilter: [val]}]
    {'foo'} /// myFilter('foo', val)
```

Хотя особых кейзов под такой инструмент не вижу.

**Comment by kobezzza** [comment]
В рамках появления механизма фильтров по умолчанию необходимо объединить флаги компиляции replaceUndef и escapeOutput в один флаг filters.

``` js
@= filters ['html', 'undef']
```

**Comment by trikadin** [comment]
Ого, можно будет свои фильтры в настройках компиляции передать? Неплохо.

**Comment by kobezzza** [comment]
> Ого, можно будет свои фильтры в настройках компиляции передать? Неплохо.

Да, но кейзов особо я пока не вижу. Это делается ради единобразия в коде.

**Comment by trikadin** [comment]
Кейзы будут. Можно будет замутить условный фильтр, который будет на выводе проверять, скажем, тип того, что выводит, и в зависимости от этого "ветвить" вывод -- объекты как JSON, например.

**Comment by kobezzza** [comment]
Да, ты прав.

**Comment by kobezzza** [comment]
**Конечный вариант синтаксиса:**

``` js
@= filters {global: [{'html': [/* аргументы */]}], local: [{'undef': []}]}
@= filters {global: ['html']}
```

**Comment by kobezzza** [comment]
Столкнулся с проблемой:

Сейчас глобальные фильтры применяются после фильтров, т.е.

``` js
foo |bar /// foo |bar |html
```

А локальные перед:

``` js
foo |bar /// foo |undef |bar |html
```

В том кейзе, как это используется сейчас это нормально (для фильтров html и undef), но не вызовет ли это путаницу?

**Comment by kobezzza** [comment]
Хорошо подумав пришёл к выводу, что это абсолютно логичное поведение, т.к. дефолтный локальный фильтр применяется к слову, а простые локальные фильтры к выражению в скобках:

``` js
(foo + 1|bar) /// ((foo|undef) + 1|bar)
```

**Comment by kobezzza** [comment]
Сделано.
