### ISSUE TITLE
Объединение блоков с прототипами

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#21]
``` js
- template foo()
  - block bar() @inline
    121
  - block foo()
    222
```

Имена таких блоков будут лежать в одном неймспейсе с простыми блоками, а для вызовов блоков, прототипов и просто функций необходимо оставить одну функцию call.

Судьба директив `proto`, `apply` и `callBlock` пока не ясна. Либо они станут приватными и будут использоваться самим СС, либо они останутся для совместимостью с СС6.

**Comment by kobezzza** [comment]
Крепко подумав, пришёл к выводу, что прототипы нужно удалить совсем. Это исторический атавизм СС, который только вводит путаницу.

Изначально прототипом был просто "побшаблон" без возможной передачи параметров, т.е. то, что по сути сейчас представляет из себя директива `putIn`. Добавление параметров и т.д. сделали прототипы похожим на функции, но всё таки это не то и поэтому были добавлены блоки.

Ещё одной причиной к удалению прототипов служит то, что они сильно замедляют трансляцию и к ним невозможно применить декораторы.

Покойтесь с миром, да здравствуют блоки и единобразие!

**Comment by trikadin** [comment]
Так ты даже inline-блоков решил не делать?

**Comment by kobezzza** [comment]
Да, я сравнил плюсы и минусы, и решил, что нах.

**Comment by kobezzza** [comment]
Сделано.
