### ISSUE TITLE
Нужно отличать "обёрнутые" параметры функции от обычных.

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/Snakeskin#22]
Короче, проблема:

```
- template container(content)
  < div.container
    {content}

- call container('Это просто текст, всё ок')

- wrap call container()
  < h1
    А вот этот заголовок надо бы вывести без фильтра html
```

**Comment by trikadin** [comment]
From #4:

> Планируется оборачивать литералы строк конструктором String и ставить кастомное свойство объекту, который будет учитывать фильтр.

Эта возможность будет целиком и полностью внутренней, ведь так? Снаружи такого сделать нельзя.

**Comment by kobezzza** [comment]
Можно, но тут уже сам человек виноват, я не могу запретить ему сделать:

```
: foo = new String('<div></div>')
? foo.unsafe = true
{foo}
```

**Comment by trikadin** [comment]
Ну вообще-то можешь. Просто сделай ключ символом, и всё.

**Comment by trikadin** [comment]
Или отнаследуйся от String и проверяй на instanceof.

**Comment by kobezzza** [comment]
> Ну вообще-то можешь. Просто сделай ключ символом, и всё.

Скомпиленый шаблон должен работать в ES5, например, для запуска в Nashorn.

> Или отнаследуйся от String и проверяй на instanceof.

Дык, что сможет запретить юзеру сделать

``` js
: foo = new UnsafeString('<div></div>')
{foo}
```

Ну разве что, пользователь не сможет передать такой параметр из JS. А так мне кажется, что это нормально, что пользователь может сам так написать, т.к. это тоже самое, что и написать `!html`.

**Comment by trikadin** [comment]
>  А так мне кажется, что это нормально, что пользователь может сам так написать, т.к. это тоже самое, что и написать !html.

Разница именно вот в этом:

> Ну разве что, пользователь не сможет передать такой параметр из JS.

Выводится элемент как html или как текст должен определять шаблон, а не данные. Поэтому такое апи должно быть только для шаблона, а не [как в Handlebars](http://handlebarsjs.com/#html-escaping).

Возможно -- возможно -- единственное исключение можно сделать для фильтров. И то, не знаю.

**Comment by kobezzza** [comment]
А как ты запретишь ему? В этом то и проблема.

> Возможно -- возможно -- единственное исключение можно сделать для фильтров. И то, не знаю.

Это уже и так есть, например фильтр default отменяет undef, а nl2br отменяет html.

**Comment by trikadin** [comment]
> А как ты запретишь ему? В этом то и проблема.

Сделать класс UnsafeString, который хранить в глобальном замыкании, но который не виден снаружи? И который не доступен из темплейта.

**Comment by kobezzza** [comment]
> Сделать класс UnsafeString, который хранить в глобальном замыкании

Я так и предлагаю.

> И который не доступен из темплейта.

Темплейт лежит в том же замыкании, что и логично, ибо фильтру HTML нужен этот консруктор который он получит из замыкания.

**Comment by trikadin** [comment]
Решено.

**Comment by trikadin** [comment]
А хотя нет -- есть один момент.

Сейчас можно передать несколько параметров в ф-цию через and. Оборачивать в unsafe нужно только строки (и, наверное, instanceof String).

**Comment by kobezzza** [comment]
Это не проблема.

**Comment by trikadin** [comment]
> Это не проблема.

Да понятно, просто написал об этом))

**Comment by kobezzza** [comment]
Сделано.
