### ISSUE TITLE
Фильтры входных параметров

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#23]
``` js
- template parent(foo |trim = '  hello ' |trim)

- template child(foo |truncate = ' bar ') /// foo |trim |truncate = ' bar '
```

Таким образом, фильтры родительского параметра всегда наследуются в дочернем и нет возможности их удалить, а вот у параметров по умолчанию только если наследуется сам параметр, а если он переопределяется - нет.

**Comment by trikadin** [comment]
Предлагаю сбрасывать фильтры, если у дочернего поменялась сигнатура.

**Comment by kobezzza** [comment]
> Предлагаю сбрасывать фильтры, если у дочернего поменялась сигнатура.

Приведи пример, я не понял.

**Comment by trikadin** [comment]
Например, так.

```
- template button(content |trim, type = "button")
  - block root
    < button type = ${type}
      - block content
        {content}

- template buttonWithIcon(@content, type) extends button
  - block content
    < i class = icon-${@icon}
    { @text }
```

**Comment by kobezzza** [comment]
Гм, несогласен. Как таковой биндинг не может влиять на изменение наследуемых параметров (например сейчас он никак не влияет на наследуемое значение по умолчанию).

``` js
- template foo(params |fromJSON)
- template bar(@params)
```

Вообще сбросить параметр можно через такой трюк:

``` js
- template foo(val |trim)
  - block def
  {val}

- template bar(val2) extends foo
  - block def
    val = val2
```

Основывается он на том, что в СС параметры наследуются по имени, а если в дочернем шаблоне параметра нет, то он становится локальной переменной.

**Comment by trikadin** [comment]
Ага, ну если по имени, то норм. Согласен. Ещё есть вопрос применения фильтра к не переданным переменным. Как будешь проверять?

**Comment by kobezzza** [comment]
> Как будешь проверять?

Никак :smile: Не переданный параметр - это параметр undefined.

А как быть с параметрами по умолчанию?

``` js
/// Должен ли параметр по умолчанию применять фильтр trim?
- template foo(bar|trim = ' foo ')
```

**Comment by trikadin** [comment]
Да, должен. И синтаксис тогда, наверное, такой:

```
- template foo(bar = ' foo ' |trim)
```

**Comment by kobezzza** [comment]
А если я захочу повесить отдельно на значение по умолчанию?

**Comment by trikadin** [comment]
В скобки? Ну хотя может ты и прав.

**Comment by kobezzza** [comment]
> В скобки? Ну хотя может ты и прав.

Да я пока сам не уверен.

**Comment by trikadin** [comment]
Надо подумать.

**Comment by kobezzza** [comment]
Сделано.
