### ISSUE TITLE
Декораторы

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#25]
Декораторы будут доступны для блоков и шаблонов (для прототипов нет, ввиду того, что нет возможности передать "ссылку").

``` js
@bar
@baz({foo1: 1, foo2: 2})
- template foo()
```

Функция декоратор будет принимать ссылку на функцию, которую врапит и сможет возвращать другую функцию.

``` js
function typograf(target) {
  return function () {
    return Typograf.exec(target.call(this, ...arguments));
  };
}
```

Декораторы будут наследоваться и в дочернем шаблоне можно будет добавлять новые декораторы. Переопределять или удалять родительские декораторы будет нельзя.

**Comment by trikadin** [comment]
Добавить пока ничего не имею. Штука гуд.

**Comment by kobezzza** [comment]
Конечный синтаксис:

``` js
- @bar
- @baz({foo1: 1, foo2: 2})
- template foo()
  ? console.log(callee.decorators) /// Данная ссылка указывает на массив декораторов для шаблона
```

**Comment by kobezzza** [comment]
Столкнулся с рядом проблем при реализации декораторов для блоков, решил отложить до лучших времён, чтобы сейчас не терять время.

Для шаблонов сделано.
