### ISSUE TITLE
Nullable параметры

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#26]
Сейчас параметры по умолчанию ставятся в случае если значение `null` или `undefined`, но иногда `null` - это рабочий параметр, поэтому предлагаю ввести оператор `?` как в JSDoc, который показывает, что значение может быть `null`.

``` js
- template foo(bar? = 'foo')
```

**Comment by trikadin** [comment]
:+1:

**Comment by kobezzza** [comment]
Для отмены этого поведения в дочернем шаблоне будет использоваться оператор `!` (опять таки взято из jsDoc).

``` js
- template foo(bar? = 'foo')
- template baz(bar!) extends foo
```

**Comment by kobezzza** [comment]
Сделано.
