### ISSUE TITLE
Добавить опцию "autoInit" 

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/Snakeskin#27]
С этой опцией файл с шаблоном(ами) будет проверять наличие Snakeskin через require (проверяя и её наличие, конечно), если нет -- в глобалке. Если же инициализироваться нечем, то ждёт явного вызова init. При таком подходе это даже не ломающее изменение, потому что если кто-то делает потом init, то snakeskin просто заменится.

**Comment by kobezzza** [comment]
После интеграции новой модульной системы инициализация больше не нужна.
