### ISSUE TITLE
Директивы decl и data

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#28]
Предлагаю объединить эти 2 директивы в одну и переименовать в **literal**:

``` js
{{ foo }} /// Скомпилится как {{ foo }}, нужно для связи с binding движками.
{{ ${1 + 2} }} /// Интерполяция работает
```

**Comment by kobezzza** [comment]
Сделано.

**Comment by trikadin** [comment]
А если нужно вывести без двойных кривых скобок?

**Comment by kobezzza** [comment]
> А если нужно вывести без двойных кривых скобок?

``` js
{{data: 1}|json}
```

Как вариант, также можно использовать расширенный синтаксис и **cdata**. Хотя действительно, в React используется `{  }`, а не `{{  }}`.

**Comment by trikadin** [comment]
Может, сделать механизм переопределения?

**Comment by kobezzza** [comment]
Есть идеи?

**Comment by trikadin** [comment]
Возможность задать открывающий и закрывающий символ в опциях.

**Comment by trikadin** [comment]
И какие-нибудь пресеты.

**Comment by kobezzza** [comment]
Ну а как ты это представляешь? Я что то не пойму твою мысль.

**Comment by trikadin** [comment]
Ну, в параметрах компиляции указывать

```
options.literalBounds = "{ }";
```

Сплитишь это значение по пробелу, и вуаля.
И можно сделать пресеты, типа, "angular", "react", у кого там ещё свой уникальный синтаксис.
Ну и, наконец, falsy-значения убирают границы вообще.

**Comment by trikadin** [comment]
Ну или не строкой, а массивом (или названием пресета).

**Comment by kobezzza** [comment]
Лучше массивом, окай.

**Comment by kobezzza** [comment]
Сделано, добавлен параметр компиляции `literalBounds = ['{{', '}}']`.

``` js
- template index(val) @= literalBounds ['<?php', '?>']
  {{ foo }}
```

**Comment by trikadin** [comment]
Лол, компилить php-код на Snakeskin -- это из разряда острых извращений.

**Comment by kobezzza** [comment]
> Лол, компилить php-код на Snakeskin -- это из разряда острых извращений.

:laughing:
