### ISSUE TITLE
Объединение call c callBlock

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#36]
Для разрешения конфликтов предлагается синтаксис стрелки:

``` js
+= foo()
+= ->foo() /// Хз, по мне как то громоздко
```

**Comment by trikadin** [comment]
Почему нельзя просто ->, без +=?

**Comment by kobezzza** [comment]
> Почему нельзя просто ->, без +=?

Можно, но мы хотели убрать различие между call и callBlock, а получается оно всё равно остаётся.

К тому же

``` js
- wrap ->foo() /// Тоже как то не аккуратно
```

**Comment by trikadin** [comment]
Э нет. Это не различие между call и callBlock --  это просто расширение ссылки.

Как `func()` и `obj.method()` в JS, только короче)

**Comment by kobezzza** [comment]
Кароч при выборе shorthand-а нужно учесть, что он будет использоватся и как директива, и как параметр для wrap и как модификатор контекста при использовании в выражении.

``` js
-> foo()
wrap ->foo()
+= bar(->foo())
```

Как видишь, выглядит несуразно как то.

**Comment by trikadin** [comment]
Хм. А какие ещё варианты, кроме стрелочки?

**Comment by kobezzza** [comment]
Вроде неплохо смотрится.

``` js
+= &foo()
wrap &foo()
+= bar(&foo())
```

**Comment by trikadin** [comment]
Не знаю...

**Comment by kobezzza** [comment]
Ну можно не выпендриваться и оставить как сейчас:

``` js
+= blocks.foo()
- wrap blocks.foo()
+= bar(blocks.foo())
```

**Comment by trikadin** [comment]
Мб заменить blocks на this/self? Насколько это будет вводить в заблуждение?

**Comment by kobezzza** [comment]
this внутри шаблона определяет сам пользователь, его трогать нельзя.

**Comment by trikadin** [comment]
Blocks длинновато. Может, реально тупо точку?..

```
+= .foo()
- wrap .foo()
+= bar(.foo())
```

Хотя она незаметная такая :С

**Comment by kobezzza** [comment]
Хз даже.

**Comment by kobezzza** [comment]
В общем будет `self.`.

**Comment by kobezzza** [comment]
Сделано
