### ISSUE TITLE
Доработка include

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#37]
Очень хочется сделать include похожим на import в JS, надо думать.

``` js
/// Старый синтаксис думаю следует оставить
- include 'foo'
- include { foo, bar as baz } from 'foo'
```

**Comment by kobezzza** [comment]
Есть предложение о введении явного экспорта для шаблонов и можно также добавить экспорт глобальных переменных:

**parent**

``` js
- export var foo = 1
- export template parent()
  Hello world!
```

**child**

``` js
- include { foo, parent } from 'parent'
```

**Comment by trikadin** [comment]
:+1: 

Собственно, в чём ты сомневаешься?)

**Comment by kobezzza** [comment]
Пока не начну реализовывать трудно сказать :)

**Comment by kobezzza** [comment]
Новый вариант улучшения include: возможность уточнения от куда взят шаблон при наследовании.

``` js
- include 'components/**/*.ss'
- template index() extends 'components/ui/button' -> index
  += 'components/ui/control' -> index()
```

Вариант с

``` js
- include { foo, parent } from 'parent'
```

плох тем, что совершенно не понятно, как это совмещать со вставкой по маске `- include 'components/**/*.ss'` и появляется необходимость делать реэкспорты шаблонов (ну т.е. как в JS).

Плюс новый вариант куда проще реализовать и он не ломает совместимость с СС6 - меньше переписывать придётся.

**Comment by kobezzza** [comment]
Пока выглядит неуклюже, думаю в данном русле...

**Comment by kobezzza** [comment]
Новая версия: ввести обязательную директиву **namespace**, без которой нельзя объявлять шаблоны и которая гарантирует уникальность модуля для каждого файла, а сам механизм реализовывать через уже существующий механизм пространств имён.

``` js
/// Можно использовать более сложное пространство имен,
/// например, block.ui.input
- namespace input 
- template index()
```

``` js
- namespace select

/// По умолчанию вычисляется главный шаблон
/// или можно задать явно
- template index() from #input
  += #dropdown()
```

Поведение здесь такое: шаблоны будут создан по неймспейсу: 

``` js
exports.tpls.input.index
exports.tpls.select.index
```

Этот вариант ещё проще реализовать и он гораздо лаконичнее.

**Comment by kobezzza** [comment]
Сделано.
