### ISSUE TITLE
Неявный вызов директивы tag

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#39]
Есть предложение, добавить новый флаг компиляции, чтобы в режиме JadeLike первое слово в предложении трактовалось как tag (как в Jade, но только для тегов, т.е. без if-ов и т.д.).

``` js
- template foo()
  .foo.bar
    | 121 /// В начале текста нужно ставить специальный символ |

  /// Или использовать директиву text
  span
    = /// shorthand для text
      Hello world!
      Hello people!
```

**Comment by trikadin** [comment]
Только не говори, что тебя так зацепило.

**Comment by trikadin** [comment]
Нахер надо.

**Comment by kobezzza** [comment]
Да это 10 строчек кода, а оператор | и так уже есть.

**Comment by trikadin** [comment]
Решать тебе, но я против, серьёзно. Это вне логики языка, и это не нужно тем, кто им пользуется)

**Comment by kobezzza** [comment]
Взвесив плюсы и минусы решил не делать.
