### ISSUE TITLE
Возможность добавлять объекту поля-шаблоны

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/Snakeskin#4]
```
- var foo = {}
- foo->bar /// присваивает foo.bar = <div><span></span></div>
  < div
    < span

- foo->some /// присваивает foo.some = <h1>123</h1>
  < h1
    123

- foo.bar // выводит значение foo.bar
```

**Comment by kobezzza** [comment]
Как я это вижу:

**Для объекта**

```
- var foo = {};
- field foo.bar
  < div
    < span
```

**Для массива**

```
- var foo = [];
- push foo
  < div
    < span
```

**Литеральная форма**

```
- map foo
  - field bar
    < div
      < span

- array foo2
  - push
    < div
      < span
```

**Использование с враперами**

```
- wrap call foo()
  /// Если не указать название, то будет создан анонимный объект
  - map foo
    - field bar
      < div
        < span
- and
  /// Если не указать название, то будет создан анонимный массив
  - array foo2
    - push
      < div
        < span
```

**Comment by trikadin** [comment]
Ты не за краткость)

**Comment by kobezzza** [comment]
Также нужно не забыть, что эти подшаблоны должны обходить html фильтр. Планируется оборачивать литералы строк конструктором String и ставить кастомное свойство объекту, который будет учитывать фильтр html.

**Comment by trikadin** [comment]
> Также нужно не забыть, что эти подшаблоны должны обходить html фильтр. Планируется оборачивать литералы строк конструктором String и ставить кастомное свойство объекту, который будет учитывать фильтр html.

Думаю, механизм должен быть одинаковым с #22 
В связи с чем предлагаю это обсуждать там.

**Comment by trikadin** [comment]
При подходе с #22 нам теперь не нужен этот синтаксис, так как ты можешь сделать тупо

```
- wrap [].push()
  < div 
```

**Comment by trikadin** [comment]
Единственное, о чём нужно подумать -- это как делать это в случае присваивания.

**Comment by kobezzza** [comment]
> При подходе с #22 нам теперь не нужен этот синтаксис, так как ты можешь сделать тупо

Чёто я вообще не понял, что тут произошло.

**Comment by kobezzza** [comment]
``` js
- target {} as foo
  * bar
    121

- target [] as bar
  * /// shorthand для putIn
    121

- var baz = []
- target baz
  *
    121

- wrap foo()
  - target []
    *
      222

- var fffuuu
- putIn fffuuu
  222
```

**Comment by trikadin** [comment]
Изменения: #42

**Comment by kobezzza** [comment]
Cделано.
