### ISSUE TITLE
Вынести директиву cdn в подключаемую библиотеку

### ISSUE THREAD

**Issue by kobezzza** [SnakeskinTpl/Snakeskin#41]
Было решено реализовать её как функцию STD библиотеки SS.

https://github.com/SnakeskinTpl/Snakeskin/blob/f110a6c5a81419bb4b3983d3d33eedc226c317b6/src/directives/cdn.js

**Comment by kobezzza** [comment]
Также решил вынести туда же директивы link, script и style.

**Comment by kobezzza** [comment]
Набросок для cdn

``` js
- template cdn(name, provider)
  - if !name
    - throw new Error('missing a name of the requested library')

  : desc = name.split('@')

  - lib = desc[0]
  - version = desc[1]

  - if !version
    - throw new Error('missing a version of the requested library')

  - target {} as libraries
    * angularjs
      - target {}
        * google
          - script (src = .../angularjs/${version}/angular.min.js)

        * yandex
          - script (src = .../angularjs/${version}/angular.min.js)

  - block libraries(list = libraries) =>

  - if !libraries[lib] 
    - throw new Error("the requested library ${name} is not found")

  {libraries[lib][provider] || (libraries[lib]|firstKey)}
```

**Comment by kobezzza** [comment]
``` js
- include { cdn as baseCDN } from 'std'
- template cdn(name, provider) extends baseCDN 
  - block libraries(list)
    - putIn list.dojo
      - target {}
        * google
          - script (src = .../dojo/${version}/dojo/dojo.js)
```

**Comment by kobezzza** [comment]
> Также решил вынести туда же директивы link, script и style.

Ещё раз подумал и отказался от этой идеи, т.к. синтаксис вызова функции не такой удобный, как у чистого tag.

**Comment by trikadin** [comment]
Слушай, а ты хочешь cdn темплейтом сделать, не через API добавления директив?

**Comment by kobezzza** [comment]
Ну да, как раз в этом и идея, т.к. это позволит модифицировать логику используя механизмы СС - наследование, примеси и т.д. (см пример выше). Хороший пример - Nib, библиотека для Stylus написанная на Stylus. Вот такуе жу штуку я хочу для SS.

**Comment by trikadin** [comment]
Да, я уже понял, что ступил, мы же это обсуждали.

**Comment by kobezzza** [comment]
https://github.com/SnakeskinTpl/std.ss/blob/master/src/html.ss

Сделано.
