### ISSUE TITLE
Изменения для wrap, target, putIn

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/Snakeskin#42]
Предлагаю сделать `putIn` отдельной директивой, и унифицировать синтаксис `target` и `wrap`:

putIn:

```
- var div
- putIn div
  < div

/// div === '<div></div>'


- var foo = {name: 'span'}
- putIn foo.example
  < span

/// foo === {name: 'span', example: '<span></span>'}
```

---

Общий синтаксис для `target` и `wrap`:
- Создаём объект:

```
- target {} as tags
  * div
    < div

  * span
    < span

  * p /// теперь только через звёздочку, это не отдельная директива, а часть синтаксиса target
    < p

/// значением tags будет {div: "<div></div>", span: "<span></span>", p: "<p></p>"}
```
- Создаём массив:

```
- target [] as headers
  * /// возможно, стоит подумать о возможности указать здесь номер элемента
    < h1

  *
    < h2

  *
    < h3

/// значением headers будет ['<h1></h1>', '<h2></h2>', '<h3></h3>']
```
- Вызываем функцию/темплейт:

```
- wrap templ()
  *
    < div

  * 
    < span

  *
    123

/// templ будет вызвана как templ('<div></div>', '<span></span>', 123)
```

Дополнительные соображения: 
- возможно, тогда стоит всё же назвать директиву `assign` :smile: 
- кстати, а что должна делать target в случае `- target foo as bar` ?

**Comment by kobezzza** [comment]
> возможно, тогда стоит всё же назвать директиву assign

Только Путин, только хардкор :laughing: 

> кстати, а что должна делать target в случае - target foo as bar

Создать новую переменную, со ссылкой на foo.

>  теперь только через звёздочку, это не отдельная директива, а часть синтаксиса target

Таки это директива, таков механизм движка СС, предлагаю пусть этим занимается всё тот же putIn.

> возможно, стоит подумать о возможности указать здесь номер элемента

Это лишнее.

---

В целом неплохо, но вот такое

``` js
- wrap foo()
  *
    121
```

Не выглядит слишком усложнённым?

``` js
- wrap foo()
  121
```

**Comment by trikadin** [comment]
Окей, тогда, по сути, меняем только вид wrap.

> Не выглядит слишком усложнённым?

Я тебе про кейс, когда несколько аргументов. Возможно, ты прав, и первую звездочку можно сделать опциональной. Тогда, мб, можно сделать то же самое и для `target` с массивами.

```
- target []
  < div
/// => ['<div></div>'] 
```

Для объектов, конечно, не получится, так как нужен ключ.

Тебе оценивать по сложности.

**Comment by kobezzza** [comment]
> Тогда, мб, можно сделать то же самое и для target с массивами.

Дело в том, что я не знаю кто там, массив или объект, поэтому дабы не городить рантайм обвязки - нах.

А что если звёздочку с wrap не вкладывать во wrap, а чейнить с ним, как сейчас and делает.

``` js
- wrap foo()
  121
*
  222
```

Хотя такая перегрузка усложнит парсинг...

**Comment by kobezzza** [comment]
Мб всё таки оставим and как ща? Мне ей Богу кажется, что это удобнее.

**Comment by trikadin** [comment]
Короче, в идеале я хочу полного однообразия `target` для массивов, `target` для объектов и `wrap`:
- Вызываем функцию/темплейт:

```
- wrap templ()
  < div /// первая звездочка опциональная для случае, когда параметр-шаблон всего один

* 13 /// указание ключа не приводит к ошибке, но он ни на что не влияет
  < span

/// templ будет вызвана как templ('<div></div>', '<span></span>', 123)
```
- Создаём массив:

```
- target []
  * /// опять же, опциональная звездочка, здесь она для примера
    < div 

  * 12 // можно указать конкретный индекс добавляемого элемента, если его нет -- берем length
    < span
```
- Создаём объект:

```
- target {}
  * div /// тоже опциональная, если ключа нет -- берется значение length (удобно для array-like объектов)
    < div

  * span
    < span

  * p
    < p
```

Итак, разницы между работой `target` для массива и для объекта нет никакой -- опциональная первая звезда, опциональный ключ, который по умолчанию равен `[[Target]].length`

Небольшое отличие лишь в случае с wrap -- там значение ключа всегда `[[ArgumentsList]].length`

**Comment by trikadin** [comment]
> Мб всё таки оставим and как ща? Мне ей Богу кажется, что это удобнее.

Остро несогласен. :-1:

**Comment by kobezzza** [comment]
Сделано, первый `putIn` опционален.

**Comment by kobezzza** [comment]
Мы не учли кейз, когда возвращаемое значение в call вставляется в target или wrap.

``` js
- target [] as foo
  += bar()
    < .foo
      121
```

**Comment by kobezzza** [comment]
Сделано, теперь call может использоваться вместе с putIn, target и другими call.

``` js
+= foo()
  += bar()
    < .foo
      121

- target [] as baz
  += foo()
    121

- var bla
- putIn bla
  += foo()
    < .foo
      121
```

Шаблоны и блоки также могут возвращать объекты, которые поймёт target.

``` js
- template foo()
  - target {} as bar
    * foo
      < .foo

  - return Data(bar)

- template bar()
  - target [] as baz
    += foo()
```

**Comment by trikadin** [comment]
Чувствую, специфицировать мы это задолбёмся.

**Comment by kobezzza** [comment]
> Чувствую, специфицировать мы это задолбёмся.

А в чём проблема?
