### ISSUE TITLE
Изменения в работе i18n

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/Snakeskin#47]
Сейчас у нас для i18n есть строковые литералы в тильдах:

``` js
`Текст-ключ`
```

=>

``` js
i18n('Текст-ключ')
```

---

Нужно добавить возможность передавать в i18n доп. параметры:
1) Задание параметра компиляции, который будет содержать ссылку на параметры:

```
- template foo(param) @= i18nOptions 'param.locale'
  {`Some text`}
```

=>

``` js
i18n('Some text', param.locale);
```

2) Локальное переопределение:

``` js
`Another text`(param.anotherLocale)
```

=>

``` js
i18n('Another text', param.anotherLocale);
```

**Comment by kobezzza** [comment]
Локальное переопределение будет работать только в режиме директивы:

``` js
{`Another text`(param.anotherLocale)}
```

**Comment by kobezzza** [comment]
Сделано.
