### ISSUE TITLE
Error with import

### ISSUE THREAD

**Issue by yazonnile** [SnakeskinTpl/Snakeskin#77]
```
- namespace modeMap
- import { a } from './test'
```

`test.js` is in same folder as current template

Got an error

```
SnakeskinError: Cannot find module './test'; 
Line: 4; 
File: PATH\template.ss; 
------------------------------
  1 {namespace modeMap}
  ...
  ...
> 4 {import { a } from './test'}
```

**Comment by kobezzza** [comment]
Fixed.

**Comment by yazonnile** [comment]
Обновился до 7.2.2 - проблема все еще существует

```
SnakeskinError: Cannot find module './sss'; 
Line: 4; 
----------------------------------
  1 {namespace modeMap}
  ...
  ...
> 4 {import * as a from './sss'}
```

sss - лежит в папке с шаблоном

**Comment by yazonnile** [comment]
Беда еще в том, что теперь и такая запись не пашет

```
- template hello()
: a = require('./sss')
```

```
Error: Cannot find module './sss'
    at Function.Module._resolveFilename (module.js:338:15)
```

**Comment by yazonnile** [comment]
временно решил через фильтр

```
: config = 'pathToMyTemplate/sss.js'|req
```

а req возвращает просто require(src)

**Comment by kobezzza** [comment]
Очень странно, на моих тестах всё ок. Нужен запускаемый пример. Также как вариант решение задачи: http://snakeskintpl.github.io/docs/api-ru.html#compile--resolveModuleSource. Возвращай абсолютный путь и всё будет ок. А вообще жду запускаемый пример, у меня ошибка не воспроизводится.

**Comment by kobezzza** [comment]
Еще важный момент: как именно запускается СС. Как галп/грант и т.д. плагин, как глобально установленный CLI, как локальный CLI и т.д.
