### ISSUE TITLE
Faster escaping function

### ISSUE THREAD

**Issue by hcodes** [SnakeskinTpl/Snakeskin#79]
https://github.com/component/escape-html

**Comment by kobezzza** [comment]
Денис, спасибо за ссылку, интересно. Но у меня экранирование более глубокое и сильно зависит от контекста, например внутри атрибутов тега также динамические переменные экранируются по javascript: параметру. Да и на самом деле экранирование у меня не является узким местом.

**Comment by hcodes** [comment]
Алгоритм интересный, в разы быстрее обычных.
