### ISSUE TITLE
Использование setFilterParams до добавления фильтра

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/Snakeskin#84]
Столкнулся с тем, что нельзя добавить параметры недобавленному фильтру. С одной стороны, это логично, с другой -- у меня сейчас компиляция темплейтов и их выполнение разнесены, и мне нет смысла добавлять фильтры на этапе компиляции. А вот параметры нужно добавлять потому, что они влият на компиляцию (в частности, биндинги). У себя это решил добавлением заглушек, но считаю, что проблема требует обсуждения.

**Comment by kobezzza** [comment]
Сделано в 7.2.5

**Comment by trikadin** [comment]
Отлично.
