### ISSUE TITLE
Проблема cо вставкой шаблона из namespace вида 'b-foo'

### ISSUE THREAD

**Issue by dmitrybrovka** [SnakeskinTpl/Snakeskin#88]
Есть некоторый шаблон в файле b-header:
```
- namespace [%fileName%]
- template index()
  Hello world!
```

Есть шаблон страницы в который встраивается шаблон выше:
```
- namespace [%fileName%]
- include './b-header/'

- template index()
   += ['b-header'].index()
```

В консоли получаю
`Error: ["b-header"].index is not a function`

Если заменить b-header на header функция index отрабатывает и шаблон вставляется в страницу.

Использую генерацию статических страниц при помощи gulp'a
```
ss({
   exec: true,
   prettyPrint: true
})
```

**Comment by kobezzza** [comment]
Это не баг. По умолчанию СС для удобства для каждого неймспейса создаёт переменную:

```
- namespace foo
```

```js
exports.foo = {};
var foo = exports.foo;
```

Когда неймпейс объявлен с квадратными скобками, то этого не происходит

```
- namespace ['foo']
```

```js
exports['foo'] = {};
```

Т.е. в твоём случае тебе нужно написать: `+= exports['b-header'].index()`

Подробнее тут: http://snakeskintpl.github.io/docs/api-ru.html#namespace

**Comment by dmitrybrovka** [comment]
Спасибо!
