### ISSUE TITLE
Cannot proxy the given URL

### ISSUE THREAD

**Issue by hcodes** [SnakeskinTpl/Snakeskin#89]
В README картинка не загружается,  может её лучше поместить в репу?
http://kobezzza.com/files/snakeskin/logo.svg?1

**Comment by kobezzza** [comment]
Угу, сделано)

**Comment by hcodes** [comment]
Появился Frank! :)

**Comment by kobezzza** [comment]
Ага!) Кстати, начал писать спеку новой версии языка: https://github.com/SnakeskinTpl/SnakeskinNext/issues - присоединяйся!
